# Generated by Django 3.0.5 on 2020-05-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='snow_days_this_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
